version: 2
sources:
  - name: raw
    database: de-zoomcamp-jhigaki-course
    schema: nyc_taxi_raw
    tables:
      - name: yellow_tripdata_2019_01_external
      - name: yellow_tripdata_2019_02_external      