version: 2
sources:
  - name: raw
    database: de-zoomcamp-jhigaki-course
    schema: nyc_taxi_raw
    tables:      
    - name: yellow_tripdata_2019_01_external
    - name: yellow_tripdata_2019_02_external
    - name: yellow_tripdata_2019_03_external
    - name: yellow_tripdata_2019_04_external
    - name: yellow_tripdata_2019_05_external
    - name: yellow_tripdata_2019_06_external
    - name: yellow_tripdata_2019_07_external
    - name: yellow_tripdata_2019_08_external
    - name: yellow_tripdata_2019_09_external
    - name: yellow_tripdata_2019_10_external
    - name: yellow_tripdata_2019_11_external
    - name: yellow_tripdata_2019_12_external
    - name: yellow_tripdata_2020_01_external
    - name: yellow_tripdata_2020_02_external
    - name: yellow_tripdata_2020_03_external
    - name: yellow_tripdata_2020_04_external
    - name: yellow_tripdata_2020_05_external
    - name: yellow_tripdata_2020_06_external
    - name: yellow_tripdata_2020_07_external
    - name: yellow_tripdata_2020_08_external
    - name: yellow_tripdata_2020_09_external
    - name: yellow_tripdata_2020_10_external
    - name: yellow_tripdata_2020_11_external
    - name: yellow_tripdata_2020_12_external


    - name: green_tripdata_2019_01_external
    - name: green_tripdata_2019_02_external
    - name: green_tripdata_2019_03_external
    - name: green_tripdata_2019_04_external
    - name: green_tripdata_2019_05_external
    - name: green_tripdata_2019_06_external
    - name: green_tripdata_2019_07_external
    - name: green_tripdata_2019_08_external
    - name: green_tripdata_2019_09_external
    - name: green_tripdata_2019_10_external
    - name: green_tripdata_2019_11_external
    - name: green_tripdata_2019_12_external
    - name: green_tripdata_2020_01_external
    - name: green_tripdata_2020_02_external
    - name: green_tripdata_2020_03_external
    - name: green_tripdata_2020_04_external
    - name: green_tripdata_2020_05_external
    - name: green_tripdata_2020_06_external
    - name: green_tripdata_2020_07_external
    - name: green_tripdata_2020_08_external
    - name: green_tripdata_2020_09_external
    - name: green_tripdata_2020_10_external
    - name: green_tripdata_2020_11_external
    - name: green_tripdata_2020_12_external

    - name: fhv_tripdata_2019_01_external
    - name: fhv_tripdata_2019_02_external
    - name: fhv_tripdata_2019_03_external
    - name: fhv_tripdata_2019_04_external
    - name: fhv_tripdata_2019_05_external
    - name: fhv_tripdata_2019_06_external
    - name: fhv_tripdata_2019_07_external
    - name: fhv_tripdata_2019_08_external
    - name: fhv_tripdata_2019_09_external
    - name: fhv_tripdata_2019_10_external
    - name: fhv_tripdata_2019_11_external
    - name: fhv_tripdata_2019_12_external   
    - name: taxi_zone_lookup_external
